#!/bin/bash -x

# TODO: these can fail if there are no results being tagged. `|| true` helps
# the hook as a whole succeed still, but this is kind of lame.


# Even though it's documented to work, notmuch-search doesn't seem to support
# AND -- something like `notmuch search --output=threads tag:muted and
# tag:INBOX` returns nothing even when each individual tag search returns
# results found in the other search. Thus, we make each search separately and
# find common threads. From https://unix.stackexchange.com/a/398143/129055


# UPDATE: it looks like the syntax we need is more complicated, because
# tag:muted will apply to previous messages, not the ones with tag:INBOX, so we
# need to intersect threads. Same idea as our merge_tag_search, but notmuch
# supports it natively
function merge_tag_search () {
    local first=1
    local res=
    local merged=
    for query in "$@"
    do
        local res=$(notmuch search --output=threads "$query" | sort)
        if [ $first -eq 1 ]
        then
            merged=$res
        else
            merged=$(comm -12 <(echo "$merged") <(echo "$res"))
        fi
        first=0

        # Break early if we're out of results already
        if [ "x$merged" == "x" ]
        then
            break
        fi
    done
    echo -n "$merged"
}

# Separate personal and work emails
notmuch tag +affirm "path:marc.sherry@affirm.com/** AND tag:new"
notmuch tag +personal "path:msherry@gmail.com/** AND tag:new"

# Flag Affirm Phabricator messages where we're a reviewer
notmuch tag +flagged 'tag:new AND tag:affirm AND "reviewer(@marc.sherry)"'

# # Mark entire threads as flagged, not just individual messages
# notmuch tag +thread_flagged $(notmuch search --output=threads tag:flagged and not tag:thread_flagged) || true

# Ensure all messages in a muted thread are muted. Uses thread:{} search
# because the muted message is presumably out of the INBOX already, so we need
# to find the associated thread instead.
notmuch tag -INBOX thread:"{tag:INBOX}" and thread:"{tag:muted}"

# New tag is removed in maildir-notmuch-sync's cleanup, no need to remove it here
# notmuch tag -new "tag:new"
